name = "trinav"
compatibility_date = "2024-06-20"

[pages]
# Build is handled by @cloudflare/next-on-pages via npm script
pages_build_output_dir = ".vercel/output/static"

[vars]
# Set these in Cloudflare dashboard or via wrangler secret
# CLOUDFLARE_AI_GATEWAY_URL = "https://.../ai-gateway"
# CLOUDFLARE_API_TOKEN = "..."
# CLOUDFLARE_ACCOUNT_ID = "..."