name = "trinav"
compatibility_date = "2024-06-20"

[pages]
# Build is handled by @cloudflare/next-on-pages via npm script
pages_build_output_dir = ".vercel/output/static"

[vars]
# Existing Cloudflare vars
CLOUDFLARE_AI_GATEWAY_URL = "$CLOUDFLARE_AI_GATEWAY_URL"
CLOUDFLARE_API_TOKEN = "$CLOUDFLARE_API_TOKEN"
CLOUDFLARE_ACCOUNT_ID = "$CLOUDFLARE_ACCOUNT_ID"
# App auth variables
APP_LOGIN_ID = "$APP_LOGIN_ID"
APP_LOGIN_PASSWORD = "$APP_LOGIN_PASSWORD"
SESSION_SECRET = "$SESSION_SECRET"
ADMIN_SEED_SECRET = "$ADMIN_SEED_SECRET"

[[kv_namespaces]]
binding = "LESSON_RAG"
id = "${LESSON_RAG_NS_ID}"
preview_id = "${LESSON_RAG_NS_ID}"

[[d1_databases]]
binding = "DB"
database_name = "trinav_users"
database_id = "${D1_DATABASE_ID}"